Repository ontohub/ontohub-backend, pull requests merged in 2018-03, with the labels that each got.

#406 Add more files to the seeds
  db/seeds/040_file_seeds.rb
  db/seeds/fixtures/ontohub.pdf
  db/seeds/fixtures/ontohub.svg.zip
Labels: approved

#399 Index seeds
  db/seeds.rb
  db/seeds/010_user_seeds.rb
  db/seeds/020_organization_seeds.rb
  db/seeds/030_repository_seeds.rb
  invoker.ini
  lib/tasks/db.rake
Labels: in review

#407 Add reasoning fields.
  Gemfile.lock
  app/graphql/types/action_type.rb
  app/graphql/types/conjecture_methods.rb
  app/graphql/types/consistency_check_attempt_type.rb
  app/graphql/types/consistency_status_enum.rb
  app/graphql/types/file_version_type.rb
  app/graphql/types/oms_type.rb
  app/graphql/types/proof_attempt_type.rb
  app/graphql/types/proof_status_enum.rb
  app/graphql/types/reasoning_attempt_type.rb
  app/jobs/process_commit_job.rb
  app/models/multi_blob.rb
  app/policies/repository_policy.rb
  lib/importing_documents_reanalyzer.rb
  lib/refs_updater.rb
  spec/graphql/mutations/git/commit_mutation_spec.rb
  spec/graphql/queries/reasoning_attempt_query_spec.rb
  spec/graphql/queries/repository/commit/file_version_query_spec.rb
  spec/graphql/queries/repository/commit/oms_query_spec.rb
  spec/graphql/queries/repository/commit/sentence_query_spec.rb
  spec/jobs/process_commit_job_spec.rb
  spec/lib/file_version_parents_creator_spec.rb
  spec/lib/importing_documents_reanalyzer_spec.rb
  spec/models/multi_blob_spec.rb
  spec/support/schema.graphql
Labels: ready for review

#419 Update bundle
  Gemfile.lock
Labels: ready for review
