Repository ontohub/ontohub-backend, pull requests merged in 2018-02, with the labels that each got.

#382 379 simplify rubocop config
  .rubocop.yml
  .rubocop_disabled.yml
  .rubocop_enabled.yml
  .rubocop_modified.yml
  Gemfile
  spec/graphql/queries/reasoner_configuration_query_spec.rb
Labels: in progress

#383 Fix Processes and Version Check in the System Tests
  .travis.yml
  app/models/version.rb
  lib/sneakers/multi_runner.rb
Labels: ready for review

#385 Use bunny publish instead of sneakers
  app/workers/mailers_worker.rb
  app/workers/post_process_hets_worker.rb
  app/workers/process_commit_worker.rb
  app/workers/repository_cloning_worker.rb
  app/workers/repository_pulling_worker.rb
  lib/hets_agent/invoker.rb
  spec/lib/hets_agent/invoker_spec.rb
Labels: approved

#387 Dont cache rabbitmq connections
  lib/hets_agent/invoker.rb
Labels: in progress

#388 Add db:truncate and db:truncate:seed tasks
  .travis.yml
  Gemfile.lock
  db/seeds/001_clear_queue.rb
  lib/tasks/db.rake
  lib/tasks/rabbitmq.rake
Labels: ready for review

#390 Update rubocop config.
  .rubocop.yml
  lib/tasks/apidoc.rake
  lib/tasks/db.rake
  lib/tasks/rabbitmq.rake
  spec/support/bunnymock_recent_history_exchange.rb
  spec/support/controller_login_helpers.rb
  spec/support/graphql_helpers.rb
  spec/support/mailer_helpers.rb
  spec/support/tempdir.rb
Labels: approved

#393 392 create a rake tastk to send the required hets version
  config/application.rb
  config/initializers/hets_agent_initializer.rb
  lib/tasks/rabbitmq.rake
  spec/initializers/hets_agent_initializer_spec.rb
Labels: in progress

#374 356 send indexing jobs on repository user organization changes
  .travis.yml
  Gemfile
  Gemfile.lock
  app/graphql/mutations/account/confirm_email_mutation.rb
  app/graphql/mutations/account/delete_account_mutation.rb
  app/graphql/mutations/account/resend_confirmation_email_mutation.rb
  app/graphql/mutations/account/resend_password_reset_email_mutation.rb
  app/graphql/mutations/account/resend_unlock_account_email_mutation.rb
  app/graphql/mutations/account/reset_password_mutation.rb
  app/graphql/mutations/account/save_account_mutation.rb
  app/graphql/mutations/account/sign_in_mutation.rb
  app/graphql/mutations/account/sign_up_mutation.rb
  app/graphql/mutations/account/unlock_account_mutation.rb
  app/graphql/mutations/organization/create_organization_mutation.rb
  app/graphql/mutations/organization/delete_organization_mutation.rb
  app/graphql/mutations/organization/save_organization_mutation.rb
  app/graphql/mutations/repository/clone_repository_mutation.rb
  app/graphql/mutations/repository/create_repository_mutation.rb
  app/graphql/mutations/repository/delete_repository_mutation.rb
  app/graphql/mutations/repository/save_repository_mutation.rb
  app/jobs/indexing_job.rb
  config/initializers/chewy.rb
  config/initializers/settings_schema.rb
  config/settings.yml
  lib/tasks/db.rake
  spec/factories/settings_factory.rb
  spec/graphql/mutations/account/delete_account_mutation_spec.rb
  spec/graphql/mutations/account/save_account_mutation_spec.rb
  spec/graphql/mutations/account/sign_up_mutation_spec.rb
  spec/graphql/mutations/organization/create_organization_mutation_spec.rb
  spec/graphql/mutations/organization/delete_organization_mutation_spec.rb
  spec/graphql/mutations/organization/save_organization_mutation_spec.rb
  spec/graphql/mutations/repository/clone_repository_mutation_spec.rb
  spec/graphql/mutations/repository/create_repository_mutation_spec.rb
  spec/graphql/mutations/repository/delete_repository_mutation_spec.rb
  spec/graphql/mutations/repository/save_repository_mutation_spec.rb
  spec/initializers/settings_schema_spec.rb
  spec/shared_examples/confirmation_email.rb
Labels: in progress

#398 Fix chewy logger.
  config/initializers/chewy.rb
Labels: in progress
